### ISSUE TITLE
Updates not working?

### ISSUE THREAD

**Issue by Soul6in6Gun** [captainturtle/r6siegetracker-gui#2]
Looks like after deployment of new patch profile update is not working - I played three days in a row (roughly) but the last records are by 17th October, none more.

**Comment by chuahou** [comment]
I am experiencing the same issue. I initially thought it was just my imagination and didn’t look closely, but seeing this made me realise it’s a legit issue.

**Comment by Soul6in6Gun** [comment]
I just tried to dig it up "what changed" since 17th October - it was a day before new patch release. Probably Ubi broke something on their side

**Comment by captainturtle** [comment]
@Soul6in6Gun Thanks for reporting it. You are right, it looks like Ubi stopped updating some stats on their end. Even main R6 site (https://game-rainbow6.ubi.com/) is not being updated. I will try to learn more about this.

**Comment by captainturtle** [comment]
Ubisoft's official tracker is still not working, so we don't have any other options but to wait.

**Comment by captainturtle** [comment]
Good news, they patched the problems with the official website with the new season. It should be working now. By the way, I have added new operators to the main package, and will be pushing an update for the GUI tonight.
